version: 2
jobs:
  test:
    docker:
    - image: qbbproject/archlinux-ci
    steps:
    - checkout
    - run: mkdir build
    - run: cd build
    - run: cmake -DCMAKE_BUILD_TYPE=Release -DCARROT_BUILD_TESTS=ON -DCARROT_ENABLE_SANITIZERS=ON  ../
    - run: make
    - run: ctest  --output-on-failure
workflows:
  version: 2
  build_and_test:
    jobs:
    - test
