version: 2.1

# Default environment
environment:
  BUILD_SHARED_LIBS: "FALSE"
  CONAN_NON_INTERACTIVE: True

test_steps: &test_steps
  steps:
    - checkout
    - run:
        name: Setup
        command: |
          apt update -y
          apt install -y ${COMPILER_PACKAGES} cmake python3-pip
          pip3 install conan
          conan user
          conan remote add --insert 0 ci-cache https://api.bintray.com/conan/qubusproject/ci-cache
          conan remote add qubusproject https://api.bintray.com/conan/qubusproject/conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          export CC=${COMPILER}-${COMPILER_MAJOR_VERSION}
          export CXX=${CXX_COMPILER}-${COMPILER_MAJOR_VERSION}
          conan install --build outdated -s build_type=${CONFIGURATION} -s compiler=${COMPILER} -s compiler.cppstd=17 -s compiler.libcxx=libstdc++11 -s compiler.version=${COMPILER_VERSION} -if build/ .
    - run:
        name: Configure
        command: |
          export CC=${COMPILER}-${COMPILER_MAJOR_VERSION}
          export CXX=${CXX_COMPILER}-${COMPILER_MAJOR_VERSION}
          cd build
          cmake -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DCARROT_BUILD_TESTS=ON -DCARROT_ENABLE_SANITIZERS=ON -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}  ../
    - run:
        name: Build
        command: |
          cd build
          make
    - run:
        name: Test
        command: |
          cd build
          ctest  --output-on-failure


jobs:
  gcc-8-release:
    docker:
      - image: ubuntu:19.04
    environment:
      COMPILER: gcc
      CXX_COMPILER: g++
      COMPILER_VERSION: "8.3"
      COMPILER_MAJOR_VERSION: "8"
      COMPILER_PACKAGES: "gcc-8 g++-8"
      CONFIGURATION: Release
      BUILD_SHARED_LIBS: "TRUE"
    <<: *test_steps

  gcc-9-release:
    docker:
      - image: ubuntu:19.04
    environment:
      COMPILER: gcc
      CXX_COMPILER: g++
      COMPILER_VERSION: "9.1"
      COMPILER_MAJOR_VERSION: "9"
      COMPILER_PACKAGES: "gcc-9 g++-9"
      CONFIGURATION: Release
      BUILD_SHARED_LIBS: "TRUE"
    <<: *test_steps

  clang-7-release:
    docker:
      - image: ubuntu:19.04
    environment:
      COMPILER: clang
      CXX_COMPILER: clang++
      COMPILER_VERSION: "7.0"
      COMPILER_MAJOR_VERSION: "7"
      COMPILER_PACKAGES: "clang-7"
      CONFIGURATION: Release
    <<: *test_steps

  clang-8-release:
    docker:
      - image: ubuntu:19.04
    environment:
      COMPILER: clang
      CXX_COMPILER: clang++
      COMPILER_VERSION: "8"
      COMPILER_MAJOR_VERSION: "8"
      COMPILER_PACKAGES: "clang-8"
      CONFIGURATION: Release
      BUILD_SHARED_LIBS: "TRUE"
    <<: *test_steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-8-release
      - gcc-9-release
      - clang-7-release
      - clang-8-release
