version: 2.1

# Default environment
environment:
  BUILD_SHARED_LIBS: "FALSE"
  CONAN_NON_INTERACTIVE: True

test_steps: &test_steps
  steps:
    - checkout
    - run:
        name: Setup
        command: |
          apt update -y
          apt install -y ${COMPILER_PACKAGES} cmake python3-pip
          pip3 install conan
          conan user
          conan remote add --insert 0 ci-cache https://api.bintray.com/conan/qubusproject/ci-cache
          conan remote add qubusproject https://api.bintray.com/conan/qubusproject/conan
          export CC=${COMPILER}
          export CXX=${CXX_COMPILER}
          conan install --build outdated -s build_type=${CONFIGURATION} -s compiler=${COMPILER} -s compiler.cppstd=17 -s compiler.libcxx=libstdc++11 -s compiler.version=${COMPILER_VERSION} -if build/ conan/ci/linux/
    - run:
        name: Configure
        command: |
          export CC=${COMPILER}
          export CXX=${CXX_COMPILER}
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DCARROT_BUILD_TESTS=ON -DCARROT_ENABLE_SANITIZERS=ON -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}  ../
    - run:
        name: Build
        command: |
          cd build
          make
    - run:
        name: Test
        command: |
          cd build
          ctest  --output-on-failure


jobs:
  gcc-10-release:
    docker:
      - image: gcc:10.1
    environment:
      COMPILER: gcc
      CXX_COMPILER: g++
      COMPILER_VERSION: "10.1"
      COMPILER_PACKAGES: "gcc g++"
      CONFIGURATION: Release
      BUILD_SHARED_LIBS: "TRUE"
    <<: *test_steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-10-release
